apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: heimdall
  namespace: heimdall
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/bashfulrobot/infra-home
