apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: heimdall
  namespace: heimdall
spec:
  interval: 15m
  path: "./apps/spitfire/heimdall/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: heimdall
