apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: longhorn-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: dustin@bashfulrobot.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the CLoudflare DNS challenge provider
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: lh-spitfire-srvrs-co-cloudflare-api-token-secret
              key: api-token
