# https://docs.cilium.io/en/latest/network/l2-announcements/#sizing-client-rate-limit
# #services = 100
# leaseRenewDeadline = 2s
# QPS = #services * (1 / leaseRenewDeadline)

# ipv6:
# enabled: false
# bpf:
#   masquerade: true

# ipam:
#   operator:
#     clusterPoolIPv4PodCIDRList: "10.244.0.0/16"
kubeProxyReplacement: true
k8sServiceHost: 172.16.1.10
k8sServicePort: 6443
k8sClientRateLimit:
  qps: 50
  burst: 100
gatewayAPI:
  enabled: true
ingressController:
  enabled: true
  loadbalancerMode: dedicated
  default: true
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 2s
  leaseRetryPeriod: 500ms
  # interface: eth0
externalIPs:
  enabled: true
